### PR TITLE
Fix ST create to support calling .cpu() on the 2D ST.

### PR DESCRIPTION
**Pull request by kumpera**

### CODE REVIEW

**Review by wanchaol — COMMENTED** [review]
it looks like the 2d parallel integration test not getting triggered in the CI https://github.com/pytorch/tau/actions/runs/3229864318/jobs/5287642613 could you check what might be happening there?

**Comment by kumpera** [comment]
> 

it's being skipped because CI has an old version of PT that doesn't support the hook

**Comment by kumpera** [comment]
The bug this fixes doesn't happen unless you're using PT master

**Comment by wanchaol** [comment]
> > 
> 
> it's being skipped because CI has an old version of PT that doesn't support the hook

I see. hmm i thought in the CI we should be using the lastest nightly https://github.com/pytorch/tau/blob/main/.github/workflows/spmd_gpu_tests.sh#L20

**Comment by kumpera** [comment]
> 

It's odd because we skip if we don't find the type  on PT. I'll add some logging to help here.

**Pull request merged**
